### ISSUE TITLE
Project name may infringe copyright of direct compatitor of Google

### ISSUE THREAD

**Issue by thedrow** [google/moveit#13]
Hi,

I'm not affiliated with [moovit](https://moovitapp.com) in any way.
I just wanted to give you a heads up in case there is a problem.

moveit is very close to moovit which could potentially present a problem for your employer, FYI.

**Comment by mcy** [comment]
Sorry, meant to get back to this sooner. I have brought this to the attention of Google Legal and has been resolved.
